---
driver:
  name: vagrant
  gui: false

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: documentation

transport:
  name: winrm
  elevated: true

platforms:
  - name: windows-2012r2
    driver:
      # mwrock/Windows2012R2 has issues related to # https://github.com/chef-cookbooks/iis/issues/280
      box: opentable/win-2012r2-standard-amd64-nocm
  - name: windows-2016
    driver:
      box: mwrock/Windows2016

suites:
  - name: default
    run_list:
      - recipe[proget-test::server_default]
  - name: iis
    run_list:
      - recipe[proget-test::server_iis]
  - name: sqlserver
    run_list:
      - recipe[proget-test::server_sqlserver]
  - name: upgrade
    run_list:
      - recipe[proget-test::server_default]
      - recipe[proget-test::server_442]
